# Generated by Django 6.0.8 on 2026-09-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_token_h_2771ed_idx',
            old_name='accounts_pa_token_h_4d4e7e_idx',
        ),
    ]
