# Generated by Django 6.0.8 on 2026-09-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rename_accounts_pa_token_h_4d4e7e_idx_accounts_pa_token_h_2771ed_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_analysis/%Y/%m/%d/')),
                ('detected_food', models.CharField(blank=True, max_length=200)),
                ('confidence', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('predictions', models.JSONField(blank=True, default=list)),
                ('estimated_portion_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_analyses', to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
