services:
  db:
    image: postgres:17
    container_name: nutrilens-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nutrilens
      POSTGRES_USER: nutrilens
      POSTGRES_PASSWORD: nutrilens_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: